version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - node -v
      - npm -v
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - git config --global user.email ""
      - git config --global user.name ""
      - git add .
      - git commit -m "new"
      - git push
